DROP DATABASE IF EXISTS rc_authentication_be; 

CREATE DATABASE rc_authentication_be;

\c rc_authentication_be;

CREATE TABLE users (
id SERIAL PRIMARY KEY,
username VARCHAR(100) UNIQUE NOT NULL,
password VARCHAR(100) NOT NULL
);

CREATE TABLE token_blacklist (
id SERIAL PRIMARY KEY,
token TEXT NOT NULL,
blacklisted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
id SERIAL PRIMARY KEY,
login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
logout_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
userId INT NOT NULL REFERENCES users(id),
login_type VARCHAR(100) NOT NULL,
last_action VARCHAR(100) NOT NULL
);